In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import util

import librosa

In [2]:
tracks = util.load('data/fma_metadata/tracks.csv')
tracks.head()

            album                                                          \
         comments        date_created date_released engineer favorites id
track_id
2               0 2008-11-26 01:44:45    2009-01-05      NaN         4  1
3               0 2008-11-26 01:44:45    2009-01-05      NaN         4  1
5               0 2008-11-26 01:44:45    2009-01-05      NaN         4  1
10              0 2008-11-26 01:45:08    2008-02-06      NaN         4  6
20              0 2008-11-26 01:45:05    2009-01-06      NaN         2  4

                                                                           \
                                        information listens producer tags
track_id
2                                           <p></p>    6073      NaN   []
3                                           <p></p>    6073      NaN   []
5                                           <p></p>    6073      NaN   []
10                                              NaN   47632      NaN   []
20        <p> "spiritual songs" from Nicky Cook</p>    2710      NaN   []

          ...       track                         \
          ... information interest language_code
track_id  ...
2         ...         NaN     4656            en
3         ...         NaN     1470            en
5         ...         NaN     1933            en
10        ...         NaN    54881            en
20        ...         NaN      978            en

                                                                              \
                                                    license listens lyricist
track_id
2         Attribution-NonCommercial-ShareAlike 3.0 Inter...    1293      NaN
3         Attribution-NonCommercial-ShareAlike 3.0 Inter...     514      NaN
5         Attribution-NonCommercial-ShareAlike 3.0 Inter...    1151      NaN
10        Attribution-NonCommercial-NoDerivatives (aka M...   50135      NaN
20        Attribution-NonCommercial-NoDerivatives (aka M...     361      NaN


         number publisher tags            title
track_id
2             3       NaN   []             Food
3             4       NaN   []     Electric Ave
5             6       NaN   []       This World
10            1       NaN   []          Freeway
20            3       NaN   []  Spiritual Level

[5 rows x 52 columns]

In [3]:
tracks_small = tracks.loc[(tracks.set.subset == 'small')]

In [4]:
set(tracks_small.track.genre_top)

{'Electronic',
 'Experimental',
 'Folk',
 'Hip-Hop',
 'Instrumental',
 'International',
 'Pop',
 'Rock'}

In [5]:
rock_small = tracks.loc[(tracks.track.genre_top == 'Rock') & (tracks.set.subset == 'small')]
electronic_small = tracks.loc[(tracks.track.genre_top == 'Electronic') & (tracks.set.subset == 'small')]
rock_small.head()

            album                                                            \
         comments        date_created date_released engineer favorites   id
track_id
182             0 2008-11-26 01:52:18    2005-04-26      NaN         0   80
255             0 2008-11-26 01:55:44    2009-01-09      NaN         0  100
256             0 2008-11-26 01:56:04    2009-01-08      NaN         1  102
368             0 2008-11-26 01:58:50    2009-01-01      NaN         1  112
459             1 2008-11-26 02:05:26    2009-01-07      NaN         1  130

                                                                              \
                                                information listens producer
track_id
182       <p><em>Worn Copy</em> is    the history of pop...    5289      NaN
255                                                     NaN    5613      NaN
256       <p>The eponymous debut from Portland, Oregon's...    4418      NaN
368       <p>What's this? One lion, two moles, two zoo k...   11086      NaN
459       <p>'Machines &amp; Muscles', a lush &amp; epic...    7652      NaN

               ...       track                         \
         tags  ... information interest language_code
track_id       ...
182        []  ...         NaN     5990            en
255        []  ...         NaN     5585            en
256        []  ...         NaN     2864            en
368        []  ...         NaN     3572            en
459        []  ...         NaN    11132            en

                                                                              \
                                                    license listens lyricist
track_id
182       Attribution-Noncommercial-No Derivative Works ...    5547      NaN
255       Attribution-Noncommercial-Share Alike 3.0 Unit...    4495      NaN
256       Attribution-NonCommercial-ShareAlike 3.0 Inter...    2311      NaN
368       Attribution-Noncommercial-No Derivative Works ...    2281      NaN
459       Attribution-NonCommercial-ShareAlike 3.0 Inter...    7765      NaN


         number publisher tags                  title
track_id
182           3       NaN   []  Jules Lost His Jewels
255          12       NaN   []      We Want to be Old
256           1       NaN   []                 Toggle
368           0       NaN   []               Vampires
459           0       NaN   []   Machines and Muscles

[5 rows x 52 columns]

In [6]:
features = util.load('data/fma_metadata/features.csv')
features.head()

feature    chroma_cens                                                    \
statistics    kurtosis
number              01        02        03        04        05        06
track_id
2             7.180653  5.230309  0.249321  1.347620  1.482478  0.531371
3             1.888963  0.760539  0.345297  2.295201  1.654031  0.067592
5             0.527563 -0.077654 -0.279610  0.685883  1.937570  0.880839
10            3.702245 -0.291193  2.196742 -0.234449  1.367364  0.998411
20           -0.193837 -0.198527  0.201546  0.258556  0.775204  0.084794

feature                                             ...   tonnetz            \
statistics                                          ...       std
number            07        08        09        10  ...        04        05
track_id                                            ...
2           1.481593  2.691455  0.866868  1.341231  ...  0.054125  0.012226
3           1.366848  1.054094  0.108103  0.619185  ...  0.063831  0.014212
5          -0.923192 -0.927232  0.666617  1.038546  ...  0.040730  0.012691
10          1.770694  1.604566  0.521217  1.982386  ...  0.074358  0.017952
20         -0.289294 -0.816410  0.043851 -0.804761  ...  0.095003  0.022492

feature                     zcr                                          \
statistics             kurtosis       max      mean    median       min
number            06         01        01        01        01        01
track_id
2           0.012111   5.758890  0.459473  0.085629  0.071289  0.000000
3           0.017740   2.824694  0.466309  0.084578  0.063965  0.000000
5           0.014759   6.808415  0.375000  0.053114  0.041504  0.000000
10          0.013921  21.434212  0.452148  0.077515  0.071777  0.000000
20          0.021355  16.669037  0.469727  0.047225  0.040039  0.000977

feature
statistics      skew       std
number            01        01
track_id
2           2.089872  0.061448
3           1.716724  0.069330
5           2.193303  0.044861
10          3.542325  0.040800
20          3.189831  0.030993

[5 rows x 518 columns]

In [7]:
rock_small_features = features.loc[rock_small.index]
print(rock_small_features.isnull().any().any())

False

In [8]:
electronic_small_features = features.loc[electronic_small.index]
print(electronic_small_features.isnull().any().any())

False

In [32]:
from scipy import stats
import warnings

def columns():
        feature_sizes = dict(chroma_stft=12, chroma_cqt=12, chroma_cens=12,
                            tonnetz=6, mfcc=20, rmse=1, zcr=1,
                            spectral_centroid=1, spectral_bandwidth=1,
                            spectral_contrast=7, spectral_rolloff=1)
        moments = ('mean', 'std', 'skew', 'kurtosis', 'median', 'min', 'max')

        columns = []
        for name, size in feature_sizes.items():
            for moment in moments:
                it = ((name, moment, '{:02d}'.format(i+1)) for i in range(size))
                columns.extend(it)

        names = ('feature', 'statistics', 'number')
        columns = pd.MultiIndex.from_tuples(columns, names=names)

        # More efficient to slice if indexes are sorted.
        return columns.sort_values()

def compute_features(tid):

    AUDIO_DIR_PATH = './data/fma_small/'

    



    features = pd.Series(index=columns(), dtype=np.float32, name=tid)

    # Catch warnings as exceptions (audioread leaks file descriptors).
    # warnings.filterwarnings('error', module='librosa')
    warnings.filterwarnings("ignore")

    def feature_stats(name, values):
        features[name, 'mean'] = np.mean(values, axis=1)
        features[name, 'std'] = np.std(values, axis=1)
        features[name, 'skew'] = stats.skew(values, axis=1)
        features[name, 'kurtosis'] = stats.kurtosis(values, axis=1)
        features[name, 'median'] = np.median(values, axis=1)
        features[name, 'min'] = np.min(values, axis=1)
        features[name, 'max'] = np.max(values, axis=1)

    try:
        filepath = util.get_audio_path(AUDIO_DIR_PATH, tid)
        x, sr = librosa.load(filepath, sr=None, mono=True)  # kaiser_fast

        print(tid)

        f = librosa.feature.zero_crossing_rate(x, frame_length=2048, hop_length=512)
        feature_stats('zcr', f)

        cqt = np.abs(librosa.cqt(x, sr=sr, hop_length=512, bins_per_octave=12,
                                 n_bins=7*12, tuning=None))
        assert cqt.shape[0] == 7 * 12
        assert np.ceil(len(x)/512) <= cqt.shape[1] <= np.ceil(len(x)/512)+1

        f = librosa.feature.chroma_cqt(C=cqt, n_chroma=12, n_octaves=7)
        feature_stats('chroma_cqt', f)
        f = librosa.feature.chroma_cens(C=cqt, n_chroma=12, n_octaves=7)
        feature_stats('chroma_cens', f)
        f = librosa.feature.tonnetz(chroma=f)
        feature_stats('tonnetz', f)

        del cqt
        stft = np.abs(librosa.stft(x, n_fft=2048, hop_length=512))
        assert stft.shape[0] == 1 + 2048 // 2
        assert np.ceil(len(x)/512) <= stft.shape[1] <= np.ceil(len(x)/512)+1
        del x

        f = librosa.feature.chroma_stft(S=stft**2, n_chroma=12)
        feature_stats('chroma_stft', f)

        f = librosa.feature.rms(S=stft)
        feature_stats('rmse', f)

        f = librosa.feature.spectral_centroid(S=stft)
        feature_stats('spectral_centroid', f)
        f = librosa.feature.spectral_bandwidth(S=stft)
        feature_stats('spectral_bandwidth', f)
        f = librosa.feature.spectral_contrast(S=stft, n_bands=6)
        feature_stats('spectral_contrast', f)
        f = librosa.feature.spectral_rolloff(S=stft)
        feature_stats('spectral_rolloff', f)

        mel = librosa.feature.melspectrogram(sr=sr, S=stft**2)
        del stft
        f = librosa.feature.mfcc(S=librosa.power_to_db(mel), n_mfcc=20)
        feature_stats('mfcc', f)

    except Exception as e:
        print('{}: {}'.format(tid, repr(e)))

    return features

In [26]:
import random

TEST_SIZE = 100

test_rock_indices = random.sample(rock_small.index.to_list(), TEST_SIZE)
test_rock = rock_small_features.loc[test_rock_indices]
test_rock.head()

test_electronic_indices = random.sample(electronic_small.index.to_list(), TEST_SIZE)
test_electronic = electronic_small_features.loc[test_electronic_indices]
test_electronic.head()

feature    chroma_cens                                                    \
statistics    kurtosis
number              01        02        03        04        05        06
track_id
58341        -0.621857 -0.827268  1.166288 -0.406874 -0.157668  0.118870
108341        4.703433  1.808634 -0.300527 -0.332133  0.075950  1.409760
30521        -1.349793 -0.389189 -1.349762 -0.048446 -0.437501  0.008197
55783         0.341091 -0.517432 -0.296068 -0.378570 -0.845190 -0.929222
123004       -1.134052  0.045281 -0.787987 -1.171631 -0.621426 -0.995592

feature                                             ...   tonnetz            \
statistics                                          ...       std
number            07        08        09        10  ...        04        05
track_id                                            ...
58341      -0.981815 -0.101330  0.135887 -0.634023  ...  0.066812  0.028229
108341      3.466098  5.985042  5.335470  5.405012  ...  0.049098  0.012957
30521       0.479524 -0.764600 -0.454264 -0.766974  ...  0.088532  0.019668
55783      -0.947049  0.493347  0.352987  0.505917  ...  0.086688  0.016675
123004     -0.898390  0.000475 -1.096448 -1.267414  ...  0.094329  0.025460

feature                     zcr                                          \
statistics             kurtosis       max      mean    median       min
number            06         01        01        01        01        01
track_id
58341       0.026996   2.895683  0.275391  0.046780  0.033203  0.002441
108341      0.012418  15.362172  0.475098  0.044880  0.034180  0.000000
30521       0.019524  -0.415852  0.291992  0.081703  0.078125  0.005371
55783       0.019016  12.206530  0.481445  0.065241  0.052246  0.000000
123004      0.028372  27.231743  0.382812  0.035148  0.027344  0.000000

feature
statistics      skew       std
number            01        01
track_id
58341       1.803143  0.036691
108341      3.213401  0.045846
30521       0.272184  0.035879
55783       2.747058  0.054529
123004      4.214546  0.035058

[5 rows x 518 columns]

In [39]:
pred_rock = pd.DataFrame(columns=columns())

for index in test_rock_indices:
    pred_rock.loc[index] = compute_features(index)

pred_elec = pd.DataFrame(columns=columns())

for index in test_electronic_indices:
    pred_elec.loc[index] = compute_features(index)

143095
139117
70813
132171
110166
44917
89704
140576
14739
113513
142418
137719
38557
143106
135372
16354
35537
117883
55714
133274
95248
107506
108992
93986
87153
126676
84291
123835
64567
122086
69781
140043
74348
137631
58540
37859
124201
143219
256
55402
825
1270
26681
106571
93950
113294
94026
137722
71715
112318
6788
66537
126667
44918
71303
108038
123834
143216
10673
124992
36526
31999
138010
3761
72288
114416
75908
71617
82462
114411
98297
14736
115766
130689
99436
91205
118279
137720
112066
113063
7872
10669
56552
126294
145068
95251
138355
106562
85027
54735
121869
255
125778
9559
112529
109355
125551
71371
53807
6517
58341
108341
30521
55783
123004
26905
125154
84486
100535
40683
17588
124755
114388
47659
114296
29037
135989
68587
45153
73125
45103
64331
109535
75762
15772
64537
99707
69195
147815
15770
123938
54335
136321
108421
141874
14869
69222
139934
72233
109538
64536
115813
85838
71420
97545
73367
84483
71512
47072
115811
116878
110109
92284
145917
92554
63065
107913
15773
84195
133015
99041
107912
32437
123936
32218
26655
123935
73370
125999
87158
72215
47070
124912
31043
97845
91619
123504
125299
52648
7011
68899
110687
44092
51785
142080
136424
85837
139994
116243
85833
105411
87645
108531
130920
93521
47660
116882
115816
73372
64332

In [41]:
pred_rock.head()

feature    chroma_cens                                                    \
statistics    kurtosis
number              01        02        03        04        05        06
143095        2.754385  0.228030 -0.602634 -0.813355 -1.191049  0.632925
139117        2.575325 -0.569804 -0.920554 -1.113657 -0.540653 -1.186232
70813         0.955502 -0.699564  0.099561  0.606668  0.811210 -0.229191
132171       -0.179041  0.159912 -0.379726 -0.705651 -0.805826 -0.332274
110166       -0.345512 -0.508951  1.520537  0.871418 -0.794581 -1.038766

feature                                             ...   tonnetz            \
statistics                                          ...       std
number            07        08        09        10  ...        04        05
143095     -0.858176 -0.922484 -0.702849  0.707199  ...  0.121672  0.038937
139117     -0.353640 -0.615089 -0.478983 -0.981981  ...  0.128231  0.049164
70813      -0.679025 -0.251169  1.929726 -0.319393  ...  0.086509  0.030487
132171     -0.688694  2.073388  6.744470 -0.561852  ...  0.114992  0.030480
110166     -0.382715  0.391988 -0.469414 -0.301012  ...  0.150581  0.053482

feature                    zcr                                          \
statistics            kurtosis       max      mean    median       min
number            06        01        01        01        01        01
143095      0.042854  0.450397  0.130371  0.057872  0.055664  0.018555
139117      0.035639 -0.092034  0.101562  0.044017  0.043945  0.004395
70813       0.036222  0.556510  0.138184  0.063448  0.062988  0.011719
132171      0.056796  0.685281  0.189941  0.053914  0.047852  0.003906
110166      0.057696  0.988441  0.170898  0.054018  0.051758  0.002930

feature
statistics      skew       std
number            01        01
143095      0.706436  0.015875
139117      0.211406  0.015139
70813       0.332491  0.017356
132171      0.938918  0.030677
110166      0.770871  0.023286

[5 rows x 518 columns]

In [40]:
pred_elec.head()

feature    chroma_cens                                                    \
statistics    kurtosis
number              01        02        03        04        05        06
58341         0.276599 -0.485956 -0.390121 -0.337855 -0.782395 -0.895010
108341        0.222791 -0.042367  1.982942  1.193250 -0.129132  1.087543
30521         0.152822 -0.461118 -0.507797 -0.572411 -1.368431 -1.081849
55783        -1.262658 -0.394576 -0.286935  0.568095 -0.923054 -0.916313
123004        0.785872  3.250067 -1.177980 -1.605234 -0.906070 -0.882304

feature                                             ...   tonnetz            \
statistics                                          ...       std
number            07        08        09        10  ...        04        05
58341      -0.034828 -1.163585  0.359661 -0.829841  ...  0.091090  0.029933
108341      2.723359  3.434629  6.605052  3.442810  ...  0.058662  0.034154
30521      -0.805505  0.519987  1.031251  0.676652  ...  0.165120  0.050884
55783      -1.268973 -0.931249  1.235775 -0.782241  ...  0.136050  0.078883
123004     -0.667070 -1.134589 -1.149285  1.066183  ...  0.208487  0.084109

feature                     zcr                                          \
statistics             kurtosis       max      mean    median       min
number            06         01        01        01        01        01
58341       0.027248   2.020954  0.275879  0.052358  0.037598  0.002930
108341      0.043247  10.258068  0.297852  0.042126  0.035156  0.000000
30521       0.070842   0.404212  0.194336  0.072748  0.067383  0.002930
55783       0.088897  -0.053715  0.167969  0.061900  0.057129  0.006348
123004      0.118686   4.316449  0.098633  0.020045  0.018066  0.001953

feature
statistics      skew       std
number            01        01
58341       1.574059  0.038274
108341      2.507685  0.035463
30521       0.788484  0.031749
55783       0.651045  0.033061
123004      1.413354  0.011882

[5 rows x 518 columns]